### PR TITLE
fix "the the" typo in 'this solution' section

### PR DESCRIPTION
**Pull request by johnstonmatt**
tiny PR for a tiny typo :)

**What**: There is a typo I found in the readme where a sentence has "the the" in a sentence, I removed one of them

**Why**: seemed easy to fix and obviously the author only intended to write "the" once

**Checklist**:

- [x] Documentation
- [N/A] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by abhijit-hota** [comment]
Since you're at it, you can also add a comma after the word, _"transformer"_ to make it clearer. Something like this:
> You provide a "transformer", the plugin does the rest.

Or a semicolon.
> You provide a "transformer"; the plugin does the rest.

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @johnstonmatt for docs

**Comment by kentcdodds** [comment]
@all-contributors please add @johnstonmatt for docs

**Pull request merged**
