### PR TITLE
fix: apply `handleHTML` to cached HTML data

### PR DESCRIPTION
**Pull request by mono0x**
**What**: Apply `handleHTML` to cached HTML data in addition to fetched HTML data.

**Why**: `handleHTML` works only for fetched HTML data. This will give different results with and without cache.

**How**: Call `handleHTML` with a common code path for fetching and using cache.

**Checklist**:

- [x] Documentation N/A
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by kentcdodds** [comment]
Could you explain the use case that requires this change and add documentation if necessary and make sure CI passes?

**Comment by mono0x** [comment]
With the current implementation, whether `handleHTML` gets called or not changes depending on the existence of the targeted content's cache prior to execution. As a result, the execution result also varies based on the cache. Therefore, if we introduce caching while utilizing handleHTML, we may not be able to achieve the same results as before its introduction. I think this behavior is not desirable for a cache.

As for CI, I don't understand how my changes caused failures. Do you know how to fix it?

**Comment by kentcdodds** [comment]
It looks like they're simple linting issues. I'm afraid I don't have time to dedicate to this package right now :(

**Comment by mono0x** [comment]
Thank you for your comment despite your busy schedule.

I have fixed the lint errors. But it seems like the lint errors are not directly related to the change in this Pull Request. Do you mind fixing another issue in a single Pull Request?

**Comment by mono0x** [comment]
I also created a dedicated lint-fixing Pull Request https://github.com/remark-embedder/core/pull/125.

**Comment by kentcdodds** [comment]
Thank you so much!

**Comment by kentcdodds** [comment]
@all-contributors please add @mono0x for code and tests

**Comment by mono0x** [comment]
Thank you for the approval!

**Pull request merged**
